### ISSUE TITLE
Breadth First Search

### ISSUE THREAD

**Issue by Rafeh01** [nryoung/algorithms#124]
<h1>Breath First Search (BFS)</h1>
I went through this but could not find anything on `Breadth First Search (BFS)`. I would really like to see an implementation of that. This is tremendously helpful for me as a college student to see how most of these high-level algorithmsare implemented, especially since I will be working with most of them soon. Also, I like knowing what the time and space complexity is of a given algorithm. Great work!

**Comment by nryoung** [comment]
Hey, thanks for the kind words.

Please feel free to open a pull request with the implementation of breadth first search. Cheers.
