### ISSUE TITLE
Port time expensive code to C/C++

### ISSUE THREAD

**Issue by karandesai-96** [nryoung/algorithms#137]
While Python is a loosely typed language - hence more convenient for a programmer, it is very slow as compared to C/C++. It would be great if the code for algorithms is ported to C/C++ and is subsequently wrapped and exposed to Python.

Final outcome would be a faster package of **algorithms** with all the functionalities intact. It can be done using `ctypes` library. Please share your thoughts over this.

**Comment by mothaibatacungmua** [comment]
Good idea, but its main purpose is used for educational. It does not need to be very fast, only need to describe fully how to a specific algorithm work.

**Comment by karandesai-96** [comment]
If educational purpose for algorithms is python specific, then it is fine, else we can try to have a great inline documentation and build in using Doxygen (specific to C, like Sphinx for Python).

**Comment by nryoung** [comment]
While this is an interesting idea, @mothaibatacungmua is correct. The main purpose is to be educational. I state in the README that they should definitely not be using these in production and instead opting for more optimized versions out there.

I am certain that if we were to add fast versions of the algorithms (either in C or C++) somebody would eventually use them in their production environment and then get mad when something broke or didn't work quite as they expected. That is something that I am not really interesting in worrying about or supporting.

**Comment by karandesai-96** [comment]
@nryoung Agreed :+1:
