### ISSUE TITLE
where is guidelines

### ISSUE THREAD

**Issue by lemon0910** [nryoung/algorithms#159]
I want to write some code for this repository, but I didn't find the guidlines, can I add some new function such as stack.top and so on.

**Comment by JoaoGFarias** [comment]
By guidelines, do you mean code standards?
Well, Python is pretty restrictive in code structure - and the [tests ran a linting process](https://github.com/nryoung/algorithms/blob/master/run_tests.py#L24).

Try to describe in your PR what you implemented ([example](https://github.com/nryoung/algorithms/pull/143)), link some page explains the algorithm and cover your code with descriptive unit tests.

You can find an algorithms TODO list [here](https://github.com/nryoung/algorithms/blob/master/TODO.rst).

**Comment by lemon0910** [comment]
ok, understand, thank you
