### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zwhitchcox** [nryoung/algorithms#75]
In the [Rabin Karp algorithm](https://github.com/nryoung/algorithms/blob/master/algorithms/searching/rabinkarp_search.py), doesn't it cost more too hash every substring to md5, rather than just use a "ready-to-go" algorithm, like the bmp or kmp?

I realize that this is probably just for illustration purposes, but I'm just wanting to make sure.

**Comment by nryoung** [comment]
I honestly don't know the answer to this and I don't really have the time to research it at the moment. Since this has been opened for a while with no answer, I am going to close it out. Please feel free to reopen with an answer.
